### PR TITLE
created AboutUs section

### PR DESCRIPTION
**Pull request by debespindola**
I created the About Us section, but I'd like to space more the image and the title, but I didn't know how much. As soon as we get the one we're going to use, it would be good to test and fix if it's not great.

### CODE REVIEW

**Comment by isaquetdiniz** [comment]
can be bug on my pc, but i think that proportion of itens is distorted

**Comment by isaquetdiniz** [comment]
- i think that aboutus text is better justify
- section name and values ​​are a bit small

**Comment by isaquetdiniz** [comment]
Try for web version (the mobile version is perfect! nice work :) )
html: font-size: 62.5%
- h1: 3.6rem
- h2: 1.8rem
-p.aboutus-text: 2.1rem
-p.values-text: 1.8rem

**Comment by debespindola** [comment]
Hey, I tried to put this references, but I was too big and strange, so I put larger as I could.
I see that this file is conflicting too... damn

**Pull request merged**
